name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build Web Component
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Test Web Component
        run: npm run test
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish --access=public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          RELEASE_VERSION: ${{ github.event.client_payload.tag }}
          SLACK_CHANNEL: tignum_web
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON: https://github.com/quintessence/slack-icons/blob/master/images/octocat-spock-slack-icon.png
          SLACK_MESSAGE: "New version deployed :rocket: Actions Web Component ${{ github.event.client_payload.tag }} new version available!"
          SLACK_TITLE: ${{ github.event.client_payload.tag }} Actions Pdf Web Component
          SLACK_USERNAME: GitHubActions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
